In [1]:
import numpy as np
print(np.__version__)


1.24.3


In [36]:
a = [10.2,20.25,30.36,40,50,70,80,90]
print(a)
b = np.array(a)
print(b)
print(b+100)

[10.2, 20.25, 30.36, 40, 50, 70, 80, 90]
[10.2  20.25 30.36 40.   50.   70.   80.   90.  ]
[110.2  120.25 130.36 140.   150.   170.   180.   190.  ]


In [34]:
b.shape
b.dtype

dtype('float64')

In [41]:
d = np.array([1,2,3,4,5,6,7,8,9,10], ndmin = 2)
print(d)

c = np.array(a, ndmin = 2)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]]
[[10.2  20.25 30.36 40.   50.   70.   80.   90.  ]]


In [44]:
d.shape
d.dtype

dtype('int32')

In [49]:
d = np.array([1,2,3,4,5,6,7,8,9,10], dtype = complex)
print(d)

c = np.array(a, ndmin = 2, dtype = complex)
print(c)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
[[10.2 +0.j 20.25+0.j 30.36+0.j 40.  +0.j 50.  +0.j 70.  +0.j 80.  +0.j
  90.  +0.j]]


In [50]:
d.dtype

dtype('complex128')

In [53]:
a = [[10,20,30,40],[50,70,80,90]]
b = np.array(a)
print(b.shape)
print(b)


(2, 4)
[[10 20 30 40]
 [50 70 80 90]]


In [54]:
a = np.array([[10,20,30,40],[50,70,80,90]])
a.shape

(2, 4)

In [57]:
a = np.array([[[10,20,30],[40,50,70]],[[80,90,60],[10,20,30]]])
print(a.shape)
print(a)

(2, 2, 3)
[[[10 20 30]
  [40 50 70]]

 [[80 90 60]
  [10 20 30]]]


In [59]:
a = np.array([[10,20,30],[40,50,70],[80,90,60],[10,20,30]])
print(a.shape)
print(a)

(4, 3)
[[10 20 30]
 [40 50 70]
 [80 90 60]
 [10 20 30]]


In [64]:
a.shape = (3,4)
print(a.shape)
print(a)

(3, 4)
[[10 20 30 40]
 [50 70 80 90]
 [60 10 20 30]]
